image: 'ruby:2.3'

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - quality

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH !~ /^\d+-/
    - if: $CI_COMMIT_TAG

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v # Print out ruby version for debugging
  - bundle install -j $(nproc) --path vendor # Install dependencies into ./vendor/ruby

# rubocop:
#   stage: test
#   script:
#     - rubocop

rspec:
  stage: test
  script:
    - rspec spec

code_quality:
  stage: quality
  cache: {}
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - when: manual
      allow_failure: true
