inherit_gem:
  prettier: rubocop.yml

Layout/EndOfLine:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Metrics/LineLength:
  Max: 100
