Layout/EndOfLine:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Layout/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 120
