Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 100

# Exclude listen from complexity analysis
Metrics/AbcSize:
  IgnoredMethods: ['listen']

Metrics/CyclomaticComplexity:
  IgnoredMethods: ['listen']

Metrics/MethodLength:
  ExcludedMethods: ['listen']

Metrics/PerceivedComplexity:
  IgnoredMethods: ['listen']
# listen

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Metrics/ModuleLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

# This just causes unexpected token tCOLON errors!
Style/HashSyntax:
  Enabled: false

Style/StderrPuts:
  Enabled: false
